### ISSUE TITLE
[1.10] Followed the tutorial but mc crashes

### ISSUE THREAD

**Issue by JAWSAWN** [dmillerw/Quadrum#24]
https://gist.github.com/JAWSAWN/df8e14721582a2c46b51a9afb6925d5b

also using oresources instead of resources if that changes anything.

**Comment by JAWSAWN** [comment]
It appears to be that traits cause problems, and without them i can't get blocks to look normal. Can you please put up example "config" and "resource" files with some examples for easier understanding?

**Comment by dmillerw** [comment]
Aware of the issue, will update the guide when I get home with the fixed
file

**Comment by dmillerw** [comment]
Fixed with v0.4.0

**Comment by JAWSAWN** [comment]
Hey, It appears to be fixed mostly. But my blocks still doesn't have any texture nor localization. Can you please please give us a download of example config and resources folders that has been pre made with one or two blocks and items? Not anything complex but it would be great to have a working folder and budge around it.
