### ISSUE TITLE
[0.7.0-1.10.2] Crash on Server

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/Quadrum#35]
Works perfectly fine in single player, items/textures load, etc.

When I set it up the same way on a server I get a crash relating to creative tab.

http://pastebin.com/GWb8s9em

I have tried with and without creative tab lines for items/blocks in config, but both crash the same way.
I can provide my config files if needed.

I guess I should add that if there are no proper config files, meaning no items/blocks to add, the mod works fine on server.

**Comment by Seyeght** [comment]
I am getting a very similar crash report on a server, any update on this?

**Comment by SPMoo66** [comment]
Not yet, as far as I know.  Hopefully now that Impractical Storage is out the author will have time to come back and fix this.

**Comment by addrever** [comment]
I am also receiving this error.

**Comment by dmillerw** [comment]
Taking a look, sorry for the delay

**Comment by SPMoo66** [comment]
Any progress on this?
I was hoping to play a modpack I've been working on for a while with a friend, and this is one of the last things that I'm waiting on.

**Comment by dmillerw** [comment]
I have it fixed in my dev environment, just have to get a release out.
Tonight or tomorrow

**Comment by SPMoo66** [comment]
I'm just gonna go ahead and poke you again since it's been a few days since then.

**Comment by Quarris** [comment]
Exactly the same error for me when I try to put it on the server.

**Comment by Azulaloi** [comment]
Are you still working on this issue?

**Comment by dmillerw** [comment]
Fixed as of 0.7.1, which I'm releasing now

**Comment by SPMoo66** [comment]
That doesn't seem to fix the problem...

https://pastebin.com/dXrgWA2e

**Comment by dmillerw** [comment]
Yep, because I'm a dumbass. Found more than 2 minutes of free time and actually fixed the issue. Release incoming

**Comment by dmillerw** [comment]
Released, look for v0.7.2
